<template>
    <div>
        <h1>Payroll System</h1>
        <!-- Payroll Information Table  -->
        <table border="1" cellspacing="0" cellpadding="5">
        <thead>
        <tr>
            <th>Employee ID</th>
            <th>Hours Worked</th>
            <th>Leave Deductions</th>
            <th>Final Salary</th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="employee in payrollData" :key="employee.employedId">
            <td>{{ employee.employeeId }}</td>
            <td>{{ employee.hoursWorked }}</td>
            <td>{{ employee.leaveDeductions }}</td>
            <td>{{ employee.finalSalary }}</td>
            <td>
            <button @click="generatePayslip(employee)">Generate Payslip</button>
            </td>
        </tr>
    </tbody>
 </table>
 <!-- Payslip Modal -->
 <div v-if="selectedEmployee" class="payslip-modal">
    <h2>Payslip for Employee {{ selectedEmployee.employeeId }}</h2>
    <p><b>Hours Worked:</b>{{ selectedEmployee.hoursWorked }}</p>
    <p><b>Leave Deductions:</b>{{ selectedEmployee.leaveDeductions }}</p>
    <p><b>Final Salary:</b>{{ selectedEmployee.finalSalary }}</p>
    <button @click="downloadPayslip">Download Payslip</button>
    <button @click="closePayslip">Close</button>
 </div>
    </div>
</template>
<script>
import {jsPDF} from "jspdf";
export default {
    data() {
        return {
    "payrollData": [
        {
            "employeeId": 1,
            "hoursWorked": 160,
            "leaveDeductions": 8,
            "finalSalary": 69500
        },
        {
            "employeeId": 2,
            "hoursWorked": 150,
            "leaveDeductions": 10,
            "finalSalary": 79000
        },
        {
            "employeeId": 3,
            "hoursWorked": 170,
            "leaveDeductions": 4,
            "finalSalary": 54800
        },
        {
            "employeeId": 4,
            "hoursWorked": 165,
            "leaveDeductions": 6,
            "finalSalary": 59700
        },
        {
            "employeeId": 5,
            "hoursWorked": 158,
            "leaveDeductions": 5,
            "finalSalary": 57850
        },
        {
            "employeeId": 6,
            "hoursWorked": 168,
            "leaveDeductions": 2,
            "finalSalary": 64800
        },
        {
            "employeeId": 7,
            "hoursWorked": 175,
            "leaveDeductions": 3,
            "finalSalary": 71800
        },
        {
            "employeeId": 8,
            "hoursWorked": 160,
            "leaveDeductions": 0,
            "finalSalary": 56000
        },
        {
            "employeeId": 9,
            "hoursWorked": 155,
            "leaveDeductions": 5,
            "finalSalary": 61500
        },
        {
            "employeeId": 10,
            "hoursWorked": 162,
            "leaveDeductions": 4,
            "finalSalary": 57750
        }
    ],
        selectedEmployee: null
};
    },
    methods: {
        // when button is clicked it generates a payslip for selected employee
        generatePayslip(employee) {
            this.selectedEmployee = employee;
        },
        // close payslip modal
        closePayslip() {
            this.selectedEmployee = null;
        },
        // Downloaded payslip as PDF
        downloadPayslip(){
            const doc = new jsPDF();
            const {employeeId, hoursWorked, leaveDeductions, finalSalary} = this.selectedEmployee;
            // Set font and font size
            doc.setFont("helvetica");
            doc.setFontSize(16);
            // Title (Payslip)
            doc.setTextColor(40, 40, 255);
            doc.text("Payslip", 105, 20, null, null, "center");
            // Add Employee Information
            doc.setFontSize(12);
            doc.setTextColor(0,0,0);
            doc.text(`Employee ID: ${employeeId}`, 20, 40);
            doc.text(`Hours Worked: ${hoursWorked}`, 20, 50);
            doc.text(`Leave Deductions: ${leaveDeductions}`, 20, 60);
            doc.text(`Final Salary: $${finalSalary.toLocaleString()}`, 20, 70);
            // Draw a line to separate the sections
            doc.setDrawColor(0, 0, 0);
            doc.line(10, 75, 200, 75);
            // Set text color for the final amount
            doc.setTextColor(0, 0, 0);
            doc.setFontSize(14);
            doc.text(`Total Amount: $${finalSalary.toLocaleString()}`, 30, 95);
            // Add a footer with page number
            doc.setFontSize(10);
            doc.text("Generated by Payroll System", 105, 270, null, null, "center");
            doc.text(`Page ${doc.internal.getNumberOfPages()}`, 200, 285, { align: "right" });
            // save PDF
            doc.save(`payslip_${employeeId}.pdf`);
        }
    }
};
</script>
<style>
table{
    width: 100%;
    margin-bottom: 20px;
    border-collapse: collapse;
}
.payroll-table th, .payroll-table td {
    padding: 12px;
    text-align: left;
    border: 1px solid #ddd
}
button {
    padding: 8px 15px;
    background-color: cadetblue;
    color: white;
    border: none;
    cursor: pointer;
}
button:hover {
    background-color: darkcyan;
}
.payslip-modal{
    margin-top: 20px;
  padding: 15px;
  background-color: #F9F9F9;
  border: 1px solid #ddd;
  border-radius: 5px;
  width: 300px;
  margin-left: auto;
  margin-right: auto;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}
payslip-modal h2 {
  text-align: center;
}
.payslip-modal p {
  margin: 10px 0;
}
h1 {
    text-align: center;
    color: #333
}
.payroll-table {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
}
.download-btn, .close-btn {
  padding: 8px 15px;
  background-color: #4CAF50;
  color: white;
  border: none;
  margin-top: 10px;
  width: 100%;
  cursor: pointer;
}
.download-btn:hover, .close-btn:hover {
  background-color: #45A049;
}
img, video {
  max-width: 100%;
  height: auto;
}
.flex-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}

.flex-item {
  flex: 1 1 100%;
  margin: 10px;
}

@media (min-width: 768px) {
  .flex-item {
    flex: 1 1 48%;
  }
}

@media (min-width: 992px) {
  .flex-item {
    flex: 1 1 31%;
  }
}
/* Base styles for all devices */
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 0;
}

.container {
  width: 100%;
  padding: 20px;
  box-sizing: border-box;
}

.header, .footer {
  background-color: #343a40;
  color: white;
  text-align: center;
  padding: 10px 0;
}

.content {
  padding: 20px;
}

/* Styles for tablets and larger screens */
@media (min-width: 768px) {
  .container {
    max-width: 750px;
    margin: 0 auto;
  }
}

/* Styles for laptops and larger screens */
@media (min-width: 992px) {
  .container {
    max-width: 970px;
  }
}

/* Styles for desktops and larger screens */
@media (min-width: 1200px) {
  .container {
    max-width: 1170px;
  }
}

</style>