<template>
  <div class="container mt-4">
    <h2 class="text-center mb-4">Payroll System</h2>

    <!-- Loading Indicator -->
    <div v-if="loading" class="text-center">Loading Payroll Data...</div>

    <!-- Error Message -->
    <div v-if="errorMessage" class="alert alert-danger text-center">{{ errorMessage }}</div>

    <!-- Payroll Information Cards -->
    <div class="row">
      <div v-for="employee in payrollData" :key="employee.employee_id" class="col-12 col-md-6 col-lg-4 mb-4">
        <div class="card">
          <div class="card-header">
            <h5>{{ employee.employee_name }} </h5>
            (Employee ID: {{ employee.employee_id }})
          </div>
          <div class="card-body">
            <p><strong>Hours Worked:</strong> {{ employee.hours_worked }}</p>
            <p><strong>Leave Deductions:</strong> {{ employee.leave_deductions }}</p>
            <p><strong>Final Salary:</strong> ${{ employee.final_salary }}</p>
            <button type="button" class="btn btn-primary btn-sm mt-2" @click="generatePayslip(employee)">
              Generate Payslip
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Payslip Modal -->
    <div v-if="selectedEmployee" class="modal fade show" style="display: block;">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Payslip for {{ selectedEmployee.employee_name }} </h5>
            (Employee ID: {{ selectedEmployee.employee_id }})
            <button type="button" class="close" @click="closePayslip">&times;</button>
          </div>
          <div class="modal-body">
            <p><strong>Hours Worked:</strong> {{ selectedEmployee.hours_worked }}</p>
            <p><strong>Leave Deductions:</strong> {{ selectedEmployee.leave_deductions }}</p>
            <p><strong>Final Salary:</strong> ${{ selectedEmployee.final_salary }}</p>
            <button type="button" class="btn btn-success btn-sm" @click="downloadPayslip">Download Payslip</button>
            <button type="button" class="btn btn-secondary btn-sm" @click="closePayslip">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';
import { jsPDF } from 'jspdf';

export default {
  data() {
    return {
      payrollData: [], // Initially empty, to be populated with API data
      selectedEmployee: null, // Selected employee for the payslip
      loading: false, // To show loading indicator while fetching data
      errorMessage: '', // To display any error that occurs
    };
  },
  mounted() {
    this.loadData(); // Call loadData to fetch data when the component is mounted
  },
  methods: {
    // Method to load payroll data
    async loadData() {
      this.loading = true;
      this.errorMessage = ''; // Clear previous errors
      try {
        const response = await axios.get('http://localhost/griffith/src/php/get_payroll.php');
        if (Array.isArray(response.data) && response.data.length > 0) {
          this.payrollData = response.data; // Populate payroll data
        } else {
          this.errorMessage = 'No payroll data available.';
        }
      } catch (error) {
        console.error('Error fetching payroll data:', error);
        this.errorMessage = 'Failed to load payroll data.';
      } finally {
        this.loading = false;
      }
    },

    // Generate payslip for selected employee
    generatePayslip(employee) {
      this.selectedEmployee = employee;
    },

    // Close payslip modal
    closePayslip() {
      this.selectedEmployee = null;
    },

    // Download payslip as PDF
    downloadPayslip() {
      const doc = new jsPDF();
      const { employee_id, employee_name, hours_worked, leave_deductions, final_salary } = this.selectedEmployee;

      // Set font and font size
      doc.setFont('helvetica');
      doc.setFontSize(16);

      // Title (Payslip)
      doc.setTextColor(40, 40, 255);
      doc.text('Payslip', 105, 20, null, null, 'center');

      // Add Employee Information
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Employee Name: ${employee_name}`, 20, 40);
      doc.text(`Employee ID: ${employee_id}`, 20, 50);
      doc.text(`Hours Worked: ${hours_worked}`, 20, 60);
      doc.text(`Leave Deductions: ${leave_deductions}`, 20, 70);
      doc.text(`Final Salary: $${final_salary.toLocaleString()}`, 20, 80);

      // Draw a line to separate the sections
      doc.setDrawColor(0, 0, 0);
      doc.line(10, 85, 200, 85);

      // Set text color for the final amount
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(14);
      doc.text(`Total Amount: $${final_salary.toLocaleString()}`, 30, 105);

      // Add a footer with page number
      doc.setFontSize(10);
      doc.text('Generated by Payroll System', 105, 270, null, null, 'center');
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, 200, 285, { align: 'right' });

      // Save the PDF
      doc.save(`payslip_${employee_id}.pdf`);
    }
  }
};
</script>

<style scoped>
/* Custom styles for the payroll system */
.container {
  padding: 20px;
}

.card {
  border: 1px solid #ccc;
  border-radius: 8px;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
}

.card-header {
  background-color: #f8f9fa;
  font-weight: bold;
}

.card-body {
  padding: 15px;
}

button {
  cursor: pointer;
}

.modal {
  display: flex;
  justify-content: center;
  align-items: center;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
}

.modal-dialog {
  max-width: 100%;
  margin: 10px;
}

.modal-content {
  background-color: white;
  padding: 20px;
  border-radius: 5px;
  width: 100%;
  max-width: 500px;
}

.modal-body {
  overflow-y: auto;
  max-height: 70vh;
}

h2 {
  color: #333;
}
</style>
